import mongoose from 'mongoose';
import CheckInQuestion from '../models/CheckInQuestion.model';
import Domain from '../models/Domain.model';

// await mongoose.connect(process.env.MONGO_URI!);


// Pasted directly from checkinQuestions.ts
const CHECKIN_DOMAINS = [
  {
    id: 'physical',
    label: 'Physical',
    icon: '🏃',
    color: '#FF6B6B',
    gradientColors: ['#FF6B6B', '#FF8E53'] as [string, string],
    questions: [
      {
        field: 'physical_steps',
        label: 'Daily Steps (Demo): How many steps did you take today?',
        type: 'number',
        min: 0,
        max: 50000,
        unit: 'steps',
        weight: 0.25,
        threshold: [
          { min_value: 0, max_value: 4999, label: 'red' },
          { min_value: 5000, max_value: 9999, label: 'yellow' },
          { min_value: 10000, max_value: 50000, label: 'green' },
        ],
      },
      {
        field: 'physical_workout_mins',
        label: 'Workout Mins (Demo): How many minutes did you work out today?',
        type: 'number',
        min: 0,
        max: 300,
        unit: 'mins',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 19, label: 'red' },
          { min_value: 20, max_value: 44, label: 'yellow' },
          { min_value: 45, max_value: 300, label: 'green' },
        ],
      },
      {
        field: 'physical_rhr',
        label: 'Resting HR (Demo): What was your lowest resting heart rate today?',
        type: 'number',
        min: 30,
        max: 200,
        unit: 'bpm',
        weight: 0.2,
        threshold: [
          { min_value: 50, max_value: 70, label: 'green' },
          { min_value: 71, max_value: 85, label: 'yellow' },
          { min_value: 86, max_value: 200, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'physical_whtr',
        label: 'Waist-to-Height (Demo): What is your waist-to-height ratio?',
        type: 'number',
        min: 0.3,
        max: 1,
        unit: 'ratio',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 0.5, label: 'green' },
          { min_value: 0.51, max_value: 0.59, label: 'yellow' },
          { min_value: 0.6, max_value: 1, label: 'red' },
        ],
      },
      {
        field: 'physical_body_fat',
        label: 'Body Fat % (Demo): What is your current body fat percentage?',
        type: 'number',
        min: 0,
        max: 60,
        unit: '%',
        weight: 0.15,
        threshold: [
          { min_value: 10, max_value: 20, label: 'green' },
          { min_value: 21, max_value: 25, label: 'yellow' },
          { min_value: 26, max_value: 60, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'physical_activity_consistency',
        label: 'Activity Consistency: How many days did you exercise in the last 7 days?',
        type: 'number',
        min: 0,
        max: 7,
        unit: 'days',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 2, label: 'red' },
          { min_value: 3, max_value: 4, label: 'yellow' },
          { min_value: 5, max_value: 7, label: 'green' },
        ],
      },
      {
        field: 'physical_hrv',
        label: 'Recovery/HRV: What is your HRV reading?',
        type: 'number',
        min: 0,
        max: 200,
        unit: 'ms',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 39, label: 'red' },
          { min_value: 40, max_value: 69, label: 'yellow' },
          { min_value: 70, max_value: 200, label: 'green' },
        ],
      },
      {
        field: 'physical_vo2_max',
        label: 'Peak VO2 Max: What is your VO2 max?',
        type: 'number',
        min: 0,
        max: 80,
        unit: 'ml/kg/min',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 34, label: 'red' },
          { min_value: 35, max_value: 44, label: 'yellow' },
          { min_value: 45, max_value: 80, label: 'green' },
        ],
      },
      {
        field: 'physical_strength_sessions',
        label: 'Strength Session: How many strength sessions did you complete this week?',
        type: 'number',
        min: 0,
        max: 14,
        unit: 'sessions',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 0, label: 'red' },
          { min_value: 1, max_value: 2, label: 'yellow' },
          { min_value: 3, max_value: 14, label: 'green' },
        ],
      },
      {
        field: 'physical_post_work_fatigue',
        label: 'Post-Work Fatigue: On a scale of 1–10, how fatigued do you feel after workouts?',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 3, label: 'green' },
          { min_value: 4, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'physical_daily_steps_coordinator',
        label: 'Daily Steps: How many steps did you take today?',
        type: 'number',
        target: 'coordinator',
        min: 0,
        max: 50000,
        unit: 'steps',
        weight: 0.05,
        threshold: [
          { min_value: 0, max_value: 3999, label: 'red' },
          { min_value: 4000, max_value: 7500, label: 'yellow' },
          { min_value: 7501, max_value: 50000, label: 'green' },
        ],
      },
      {
        field: 'physical_restful_sleep_hours_coordinator',
        label: 'Restful Sleep (Hours): How many hours of restful sleep did you get?',
        type: 'number',
        target: 'coordinator',
        min: 0,
        max: 24,
        unit: 'hours',
        weight: 0.06,
        threshold: [
          { min_value: 0, max_value: 5.49, label: 'red' },
          { min_value: 5.5, max_value: 7, label: 'yellow' },
          { min_value: 7.01, max_value: 24, label: 'green' },
        ],
      },
      {
        field: 'physical_energy_coordinator',
        label: 'Physical Energy: Rate your physical energy from 1 to 10',
        type: 'scale',
        target: 'coordinator',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.04,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
    ],
  },
  {
    id: 'nutrition',
    label: 'Nutrition',
    icon: '🥗',
    color: '#4ADE80',
    gradientColors: ['#4ADE80', '#22D3EE'] as [string, string],
    questions: [
      {
        field: 'nutrition_water',
        label: 'Water Intake (Demo): How many liters of water did you drink today?',
        type: 'number',
        min: 0,
        max: 10,
        unit: 'liters',
        weight: 0.25,
        threshold: [
          { min_value: 0, max_value: 1.4, label: 'red' },
          { min_value: 1.5, max_value: 2.9, label: 'yellow' },
          { min_value: 3.0, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'nutrition_fasting_glucose',
        label: 'Fasting Glucose (Demo): What was your fasting glucose?',
        type: 'number',
        min: 50,
        max: 300,
        unit: 'mg/dL',
        weight: 0.2,
        threshold: [
          { min_value: 70, max_value: 99, label: 'green' },
          { min_value: 100, max_value: 125, label: 'yellow' },
          { min_value: 126, max_value: 300, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'nutrition_protein_intake',
        label: 'Protein Intake (Demo): How many grams per kg did you consume?',
        type: 'number',
        min: 0,
        max: 4,
        unit: 'g/kg',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 0.99, label: 'red' },
          { min_value: 1.0, max_value: 1.5, label: 'yellow' },
          { min_value: 1.6, max_value: 2.2, label: 'green' },
        ],
      },
      {
        field: 'nutrition_hba1c',
        label: 'HbA1c (Demo): What is your HbA1c percentage?',
        type: 'number',
        min: 3,
        max: 15,
        unit: '%',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 5.6, label: 'green' },
          { min_value: 5.7, max_value: 6.4, label: 'yellow' },
          { min_value: 6.5, max_value: 15, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'nutrition_processed_food',
        label: 'Processed Food (Demo): How many servings this week?',
        type: 'number',
        min: 0,
        max: 50,
        unit: 'servings',
        weight: 0.15,
        threshold: [
          { min_value: 0, max_value: 2, label: 'green' },
          { min_value: 3, max_value: 5, label: 'yellow' },
          { min_value: 6, max_value: 50, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'nutrition_post_prandial_spike',
        label: 'Post-Prandial Spike: What was your peak post-meal glucose?',
        type: 'number',
        min: 50,
        max: 400,
        unit: 'mg/dL',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 139, label: 'green' },
          { min_value: 140, max_value: 199, label: 'yellow' },
          { min_value: 200, max_value: 400, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'nutrition_triglycerides',
        label: 'Triglycerides: What are your triglyceride levels?',
        type: 'number',
        min: 50,
        max: 500,
        unit: 'mg/dL',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 149, label: 'green' },
          { min_value: 150, max_value: 199, label: 'yellow' },
          { min_value: 200, max_value: 500, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'nutrition_fiber',
        label: 'Fiber Intake: How many grams of fiber per day?',
        type: 'number',
        min: 0,
        max: 100,
        unit: 'grams',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 19, label: 'red' },
          { min_value: 20, max_value: 34, label: 'yellow' },
          { min_value: 35, max_value: 100, label: 'green' },
        ],
      },
      {
        field: 'nutrition_alcohol_units',
        label: 'Alcohol Units: How many units per week?',
        type: 'number',
        min: 0,
        max: 50,
        unit: 'units/wk',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 3, label: 'green' },
          { min_value: 4, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 50, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'nutrition_caffeine_timing',
        label: 'Caffeine Timing: How many hours before sleep was your last caffeine?',
        type: 'number',
        min: 0,
        max: 24,
        unit: 'hrs pre-sleep',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 5, label: 'red' },
          { min_value: 6, max_value: 9, label: 'yellow' },
          { min_value: 10, max_value: 24, label: 'green' },
        ],
      },
      {
        field: 'nutrition_hydration_liters_coordinator',
        label: 'Hydration (Liters): How many liters of water did you drink today?',
        type: 'number',
        target: 'coordinator',
        min: 0,
        max: 10,
        unit: 'liters',
        weight: 0.05,
        threshold: [
          { min_value: 0, max_value: 0.99, label: 'red' },
          { min_value: 1.0, max_value: 2.0, label: 'yellow' },
          { min_value: 2.01, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'nutrition_whole_vs_processed_foods_coordinator',
        label: 'Whole vs Processed Foods: Did you mostly eat whole foods today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.04,
      },
      {
        field: 'nutrition_high_added_sugar_intake_coordinator',
        label: 'High Added Sugar Intake: Did you consume high added sugar today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.04,
        invertedScore: true,
      },
    ],
  },
  {
    id: 'mental',
    label: 'Mental',
    icon: '🧠',
    color: '#A78BFA',
    gradientColors: ['#A78BFA', '#EC4899'] as [string, string],
    questions: [
      {
        field: 'mental_daily_stress',
        label: 'Daily Stress (Demo): Rate your stress level today',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.25,
        threshold: [
          { min_value: 1, max_value: 3, label: 'green' },
          { min_value: 4, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'mental_mood_score',
        label: 'Mood Score (Demo): Rate your mood today',
        type: 'scale',
        min: 1,
        max: 5,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.2,
        threshold: [
          { min_value: 1, max_value: 2, label: 'red' },
          { min_value: 3, max_value: 3, label: 'yellow' },
          { min_value: 4, max_value: 5, label: 'green' },
        ],
      },
      {
        field: 'mental_burnout_index',
        label: 'Burnout Index (Demo): How burned out do you feel?',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.2,
        threshold: [
          { min_value: 1, max_value: 2, label: 'green' },
          { min_value: 3, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'mental_anxiety_level',
        label: 'Anxiety Level (Demo): GAD-7 score',
        type: 'number',
        min: 0,
        max: 21,
        unit: 'GAD-7',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 4, label: 'green' },
          { min_value: 5, max_value: 9, label: 'yellow' },
          { min_value: 10, max_value: 21, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'mental_mindful_mins',
        label: 'Mindful Mins (Demo): How many mindful minutes today?',
        type: 'number',
        min: 0,
        max: 120,
        unit: 'mins',
        weight: 0.15,
        threshold: [
          { min_value: 0, max_value: 9, label: 'red' },
          { min_value: 10, max_value: 19, label: 'yellow' },
          { min_value: 20, max_value: 120, label: 'green' },
        ],
      },
      {
        field: 'mental_cortisol_morning',
        label: 'Cortisol (Morning): Morning cortisol level',
        type: 'number',
        min: 0,
        max: 60,
        unit: 'mcg/dL',
        weight: 0,
        threshold: [
          { min_value: 5, max_value: 23, label: 'green' },
          { min_value: 24, max_value: 29, label: 'yellow' },
          { min_value: 30, max_value: 60, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'mental_social_withdrawal',
        label: 'Social Withdrawal: How would you rate social withdrawal?',
        type: 'dropdown',
        options: ['Low', 'Medium', 'High'],
        weight: 0,
        invertedScore: true,
      },
      {
        field: 'mental_cognitive_load',
        label: 'Cognitive Load: How mentally taxed do you feel?',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'green' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'mental_journaling_freq',
        label: 'Journaling Freq: How many days did you journal this week?',
        type: 'number',
        min: 0,
        max: 7,
        unit: 'days/wk',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 1, label: 'red' },
          { min_value: 2, max_value: 4, label: 'yellow' },
          { min_value: 5, max_value: 7, label: 'green' },
        ],
      },
      {
        field: 'mental_resilience_score',
        label: 'Resilience Score: Rate your resilience',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'mental_focus_bandwidth_coordinator',
        label: 'Focus & Bandwidth: Rate your focus and mental bandwidth from 1 to 10',
        type: 'scale',
        target: 'coordinator',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.04,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'mental_overwhelmed_coordinator',
        label: 'Mentally Overwhelmed: Did you feel mentally overwhelmed today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.05,
        invertedScore: true,
      },
      {
        field: 'mental_engaging_activity_coordinator',
        label: 'Mentally Engaging Activity: Did you do a mentally engaging activity today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.02,
      },
      {
        field: 'emotional_overall_mood_state_coordinator',
        label: 'Overall Mood/State: Rate your overall mood from 1 to 10',
        type: 'scale',
        target: 'coordinator',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.05,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'emotional_extended_frustration_coordinator',
        label: 'Extended Frustration: Did you feel extended frustration today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.04,
        invertedScore: true,
      },
      {
        field: 'emotional_intentional_decompression_coordinator',
        label: 'Intentional Decompression: Did you intentionally decompress today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'sleep',
    label: 'Sleep',
    icon: '🌙',
    color: '#38BDF8',
    gradientColors: ['#1E3A5F', '#38BDF8'] as [string, string],
    questions: [
      {
        field: 'sleep_total_sleep',
        label: 'Total Sleep (Demo): How many hours did you sleep?',
        type: 'number',
        min: 0,
        max: 12,
        unit: 'hours',
        weight: 0.3,
        threshold: [
          { min_value: 0, max_value: 4.9, label: 'red' },
          { min_value: 5.0, max_value: 6.9, label: 'yellow' },
          { min_value: 7.0, max_value: 9.0, label: 'green' },
        ],
      },
      {
        field: 'sleep_deep_sleep',
        label: 'Deep Sleep (Demo): What % of your sleep was deep sleep?',
        type: 'number',
        min: 0,
        max: 100,
        unit: '%',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 9, label: 'red' },
          { min_value: 10, max_value: 14, label: 'yellow' },
          { min_value: 15, max_value: 25, label: 'green' },
        ],
      },
      {
        field: 'sleep_recovery_score',
        label: 'Recovery Score (Demo): What is your recovery score?',
        type: 'number',
        min: 0,
        max: 100,
        unit: '%',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 39, label: 'red' },
          { min_value: 40, max_value: 69, label: 'yellow' },
          { min_value: 70, max_value: 100, label: 'green' },
        ],
      },
      {
        field: 'sleep_efficiency',
        label: 'Sleep Efficiency (Demo): What was your sleep efficiency?',
        type: 'number',
        min: 0,
        max: 100,
        unit: '%',
        weight: 0.15,
        threshold: [
          { min_value: 0, max_value: 79, label: 'red' },
          { min_value: 80, max_value: 89, label: 'yellow' },
          { min_value: 90, max_value: 100, label: 'green' },
        ],
      },
      {
        field: 'sleep_rem_sleep',
        label: 'REM Sleep (Demo): What % of your sleep was REM?',
        type: 'number',
        min: 0,
        max: 100,
        unit: '%',
        weight: 0.15,
        threshold: [
          { min_value: 0, max_value: 14, label: 'red' },
          { min_value: 15, max_value: 19, label: 'yellow' },
          { min_value: 20, max_value: 25, label: 'green' },
        ],
      },
      {
        field: 'sleep_hrv_recovery',
        label: 'HRV (Recovery): What is your HRV?',
        type: 'number',
        min: 0,
        max: 200,
        unit: 'ms',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 39, label: 'red' },
          { min_value: 40, max_value: 69, label: 'yellow' },
          { min_value: 70, max_value: 200, label: 'green' },
        ],
      },
      {
        field: 'sleep_resting_hr',
        label: 'Resting HR (Sleep): What was your lowest resting heart rate?',
        type: 'number',
        min: 30,
        max: 200,
        unit: 'bpm',
        weight: 0,
        threshold: [
          { min_value: 50, max_value: 70, label: 'green' },
          { min_value: 71, max_value: 85, label: 'yellow' },
          { min_value: 86, max_value: 200, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'sleep_respiratory_rate',
        label: 'Respiratory Rate: What is your respiratory rate?',
        type: 'number',
        min: 5,
        max: 40,
        unit: 'rpm',
        weight: 0,
        threshold: [
          { min_value: 12, max_value: 16, label: 'green' },
          { min_value: 17, max_value: 20, label: 'yellow' },
          { min_value: 21, max_value: 40, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'sleep_oxygen_sat',
        label: 'Oxygen Sat (SpO2): What was your SpO2?',
        type: 'number',
        min: 80,
        max: 100,
        unit: '%',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 91, label: 'red' },
          { min_value: 92, max_value: 94, label: 'yellow' },
          { min_value: 95, max_value: 100, label: 'green' },
        ],
      },
      {
        field: 'sleep_wakeup_readiness',
        label: 'Wakeup Readiness: How ready do you feel on waking?',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
    ],
  },
  {
    id: 'reproductive',
    label: 'Reproductive',
    icon: '🌸',
    color: '#F472B6',
    gradientColors: ['#F472B6', '#FB7185'] as [string, string],
    questions: [
      {
        field: 'repro_energy_levels',
        label: 'Energy Levels (Demo): Rate your energy today',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.25,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'repro_libido_drive',
        label: 'Libido / Drive (Demo): Rate your libido/drive',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.25,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'repro_cycle_regularity',
        label: 'Cycle Regularity (Demo): Average cycle length (days)',
        type: 'number',
        min: 10,
        max: 60,
        unit: 'days',
        weight: 0.2,
        threshold: [
          { min_value: 24, max_value: 32, label: 'green' },
          { min_value: 33, max_value: 38, label: 'yellow' },
          { min_value: 39, max_value: 60, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'repro_symptom_load',
        label: 'Symptom Load (Demo): Rate symptom load',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 2, label: 'green' },
          { min_value: 3, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'repro_mood_stability',
        label: 'Mood Stability (Demo): Rate your mood stability',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'repro_basal_temp',
        label: 'Basal Temp (v2.0): Morning basal temperature',
        type: 'number',
        min: 34,
        max: 42,
        unit: '°C',
        weight: 0,
      },
      {
        field: 'repro_luteal_phase_length',
        label: 'Luteal Phase Length: Luteal phase length (days)',
        type: 'number',
        min: 5,
        max: 20,
        unit: 'days',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 9, label: 'red' },
          { min_value: 10, max_value: 11, label: 'yellow' },
          { min_value: 12, max_value: 14, label: 'green' },
        ],
      },
      {
        field: 'repro_cervical_mucus',
        label: 'Cervical Mucus: What best describes today?',
        type: 'dropdown',
        options: ['Clear/Stretch', 'Sticky/Dry', 'None'],
        weight: 0,
        invertedScore: true,
      },
      {
        field: 'repro_ovulation_window',
        label: 'Ovulation Window: Current ovulation status',
        type: 'dropdown',
        options: ['Predicted', 'Delayed', 'Missed'],
        weight: 0,
        invertedScore: true,
      },
      {
        field: 'repro_partner_connection',
        label: 'Partner Connection: Rate partner connection',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'vitality_physical_drive_coordinator',
        label: 'Physical Drive/Vitality: Rate your physical drive and vitality from 1 to 10',
        type: 'scale',
        target: 'coordinator',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.06,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'vitality_intimacy_satisfaction_coordinator',
        label: 'Intimacy Satisfaction: Are you satisfied with intimacy in your life currently?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.04,
      },
    ],
  },
  {
    id: 'financial',
    label: 'Financial',
    icon: '💰',
    color: '#FBBF24',
    gradientColors: ['#FBBF24', '#F59E0B'] as [string, string],
    questions: [
      {
        field: 'finance_savings_percent',
        label: 'Savings % (Demo): What % of income do you save?',
        type: 'number',
        min: 0,
        max: 100,
        unit: '%',
        weight: 0.25,
        threshold: [
          { min_value: 0, max_value: 9, label: 'red' },
          { min_value: 10, max_value: 19, label: 'yellow' },
          { min_value: 20, max_value: 100, label: 'green' },
        ],
      },
      {
        field: 'finance_emergency_fund',
        label: 'Emergency Fund (Demo): Months of coverage',
        type: 'number',
        min: 0,
        max: 24,
        unit: 'months',
        weight: 0.25,
        threshold: [
          { min_value: 0, max_value: 2.9, label: 'red' },
          { min_value: 3.0, max_value: 5.9, label: 'yellow' },
          { min_value: 6.0, max_value: 24, label: 'green' },
        ],
      },
      {
        field: 'finance_debt_to_income',
        label: 'Debt-to-Income (Demo): What is your DTI ratio?',
        type: 'number',
        min: 0,
        max: 100,
        unit: '%',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 15, label: 'green' },
          { min_value: 16, max_value: 35, label: 'yellow' },
          { min_value: 36, max_value: 100, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'finance_budget_adherence',
        label: 'Budget Adherence (Demo): Rate budget adherence',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'finance_financial_security',
        label: 'Financial Security (Demo): Rate financial security',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'finance_passive_income_coverage',
        label: 'Passive Income Coverage: % covered',
        type: 'number',
        min: 0,
        max: 100,
        unit: '%',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 9, label: 'red' },
          { min_value: 10, max_value: 49, label: 'yellow' },
          { min_value: 50, max_value: 100, label: 'green' },
        ],
      },
      {
        field: 'finance_net_worth_trend',
        label: 'Net Worth Trend: Current trend',
        type: 'dropdown',
        options: ['Uptrend', 'Stable', 'Downtrend'],
        weight: 0,
        invertedScore: true,
      },
      {
        field: 'finance_impulse_spending',
        label: 'Impulse Spending: How many times this week?',
        type: 'number',
        min: 0,
        max: 20,
        unit: 'count',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 1, label: 'green' },
          { min_value: 2, max_value: 4, label: 'yellow' },
          { min_value: 5, max_value: 20, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'finance_investment_literacy',
        label: 'Investment Literacy: Rate investment literacy',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'finance_insurance_coverage',
        label: 'Insurance Coverage: Coverage status',
        type: 'dropdown',
        options: ['Full', 'Partial', 'None'],
        weight: 0,
        invertedScore: true,
      },
      {
        field: 'financial_stress_anxiety_coordinator',
        label: 'Financial Stress/Anxiety: Rate your financial stress from 1 to 10',
        type: 'scale',
        target: 'coordinator',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.05,
        threshold: [
          { min_value: 1, max_value: 3, label: 'green' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'red' },
        ],
      },
      {
        field: 'financial_spending_comfort_coordinator',
        label: 'Spending Comfort: Do you feel comfortable with your current spending?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.03,
      },
      {
        field: 'financial_budget_clarity_coordinator',
        label: 'Budget Clarity: Do you have clarity on your budget?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'tech',
    label: 'Tech & Digital',
    icon: '📱',
    color: '#34D399',
    gradientColors: ['#34D399', '#059669'] as [string, string],
    questions: [
      {
        field: 'tech_total_screen_time',
        label: 'Total Screen Time (Demo): How many hours today?',
        type: 'number',
        min: 0,
        max: 24,
        unit: 'hours',
        weight: 0.3,
        threshold: [
          { min_value: 0, max_value: 3.9, label: 'green' },
          { min_value: 4.0, max_value: 7.0, label: 'yellow' },
          { min_value: 7.1, max_value: 24, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'tech_night_use',
        label: 'Night Use / Blue Light (Demo): Minutes of night device use?',
        type: 'number',
        min: 0,
        max: 300,
        unit: 'mins',
        weight: 0.25,
        threshold: [
          { min_value: 0, max_value: 15, label: 'green' },
          { min_value: 16, max_value: 45, label: 'yellow' },
          { min_value: 46, max_value: 300, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'tech_social_media_usage',
        label: 'Social Media Usage (Demo): Hours spent on social media?',
        type: 'number',
        min: 0,
        max: 12,
        unit: 'hours',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 0.9, label: 'green' },
          { min_value: 1.0, max_value: 2.5, label: 'yellow' },
          { min_value: 2.6, max_value: 12, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'tech_focus_work_blocks',
        label: 'Focus Work Blocks (Demo): How many deep work blocks?',
        type: 'number',
        min: 0,
        max: 10,
        unit: 'count',
        weight: 0.15,
        threshold: [
          { min_value: 0, max_value: 0, label: 'red' },
          { min_value: 1, max_value: 2, label: 'yellow' },
          { min_value: 3, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'tech_digital_fatigue_score',
        label: 'Digital Fatigue Score (Demo): Rate digital fatigue',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.1,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'tech_notification_pickups',
        label: 'Notification Pickups: How many pickups?',
        type: 'number',
        min: 0,
        max: 300,
        unit: 'count',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 50, label: 'green' },
          { min_value: 51, max_value: 100, label: 'yellow' },
          { min_value: 101, max_value: 300, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'tech_app_switching_frequency',
        label: 'App Switching Frequency: Rate your app switching',
        type: 'dropdown',
        options: ['Low', 'Medium', 'High'],
        weight: 0,
        invertedScore: true,
      },
      {
        field: 'tech_dopamine_seeking',
        label: 'Dopamine Seeking: Rate dopamine seeking',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 3, label: 'green' },
          { min_value: 4, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'tech_device_free_windows',
        label: 'Device-Free Windows: Hours without devices',
        type: 'number',
        min: 0,
        max: 12,
        unit: 'hours',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 0.49, label: 'red' },
          { min_value: 0.5, max_value: 1.9, label: 'yellow' },
          { min_value: 2.0, max_value: 12, label: 'green' },
        ],
      },
      {
        field: 'tech_neck_posture',
        label: 'Tech-Neck Posture: Rate posture',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Poor',
        highLabel: 'Great',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'digital_non_work_screen_time_coordinator',
        label: 'Non-Work Screen Time (Hrs): How many hours of non-work screen time did you have?',
        type: 'number',
        target: 'coordinator',
        min: 0,
        max: 24,
        unit: 'hours',
        weight: 0.04,
        threshold: [
          { min_value: 0, max_value: 1.99, label: 'green' },
          { min_value: 2, max_value: 4, label: 'yellow' },
          { min_value: 4.01, max_value: 24, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'digital_device_distraction_coordinator',
        label: 'Device Distraction: Did devices distract you significantly today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.05,
        invertedScore: true,
      },
    ],
  },
  {
    id: 'social',
    label: 'Social',
    icon: '🤝',
    color: '#60A5FA',
    gradientColors: ['#60A5FA', '#3B82F6'] as [string, string],
    questions: [
      {
        field: 'social_quality_interaction',
        label: 'Quality Interaction (Demo): How many quality interactions?',
        type: 'number',
        min: 0,
        max: 20,
        unit: 'count',
        weight: 0.25,
        threshold: [
          { min_value: 0, max_value: 0, label: 'red' },
          { min_value: 1, max_value: 1, label: 'yellow' },
          { min_value: 2, max_value: 20, label: 'green' },
        ],
      },
      {
        field: 'social_loneliness_score',
        label: 'Loneliness Score (Demo): Rate loneliness',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.25,
        threshold: [
          { min_value: 1, max_value: 2, label: 'green' },
          { min_value: 3, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'social_support_system',
        label: 'Support System (Demo): Rate your support system',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.2,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'social_conflict_level',
        label: 'Conflict Level (Demo): Rate conflict level',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 2, label: 'green' },
          { min_value: 3, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'social_trust_safety',
        label: 'Trust & Safety (Demo): Rate trust and safety',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'social_active_listening',
        label: 'Active Listening: Rate active listening',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'social_community_involvement',
        label: 'Community Involvement: Hours per week',
        type: 'number',
        min: 0,
        max: 20,
        unit: 'hours',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 0.49, label: 'red' },
          { min_value: 0.5, max_value: 1.9, label: 'yellow' },
          { min_value: 2.0, max_value: 20, label: 'green' },
        ],
      },
      {
        field: 'social_digital_vs_inperson',
        label: 'Digital vs In-Person: Ratio',
        type: 'number',
        min: 0,
        max: 10,
        unit: 'ratio',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 1.99, label: 'green' },
          { min_value: 2.0, max_value: 3.0, label: 'yellow' },
          { min_value: 3.01, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'social_vulnerability_score',
        label: 'Vulnerability Score: Rate vulnerability',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'social_boundary_setting',
        label: 'Boundary Setting: Rate boundary setting',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'social_meaningful_connection_coordinator',
        label: 'Meaningful Connection: Did you have a meaningful connection today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.04,
      },
      {
        field: 'social_reliable_support_system_coordinator',
        label: 'Reliable Support System: Do you have a reliable support system right now?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.05,
      },
    ],
  },
  {
    id: 'occupational',
    label: 'Work',
    icon: '💼',
    color: '#FB923C',
    gradientColors: ['#FB923C', '#EF4444'] as [string, string],
    questions: [
      {
        field: 'work_hours',
        label: 'Work Hours (Demo): How many hours did you work today?',
        type: 'number',
        min: 0,
        max: 24,
        unit: 'hours',
        weight: 0.25,
        threshold: [
          { min_value: 6.0, max_value: 8.0, label: 'green' },
          { min_value: 9.0, max_value: 11.0, label: 'yellow' },
          { min_value: 11.1, max_value: 24, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'work_burnout_risk',
        label: 'Burnout Risk (Demo): Rate burnout risk',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.25,
        threshold: [
          { min_value: 1, max_value: 2, label: 'green' },
          { min_value: 3, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'work_break_frequency',
        label: 'Break Frequency (Demo): How many breaks today?',
        type: 'number',
        min: 0,
        max: 20,
        unit: 'count',
        weight: 0.2,
        threshold: [
          { min_value: 0, max_value: 1, label: 'red' },
          { min_value: 2, max_value: 3, label: 'yellow' },
          { min_value: 4, max_value: 20, label: 'green' },
        ],
      },
      {
        field: 'work_flow_state',
        label: 'Flow State (Demo): Rate flow state',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'work_job_satisfaction',
        label: 'Job Satisfaction (Demo): Rate job satisfaction',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.15,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'work_cognitive_load',
        label: 'Cognitive Load: Rate cognitive load',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 3, max_value: 5, label: 'green' },
          { min_value: 6, max_value: 8, label: 'yellow' },
          { min_value: 9, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'work_physical_desk_time',
        label: 'Physical Desk Time: Hours at desk',
        type: 'number',
        min: 0,
        max: 24,
        unit: 'hours',
        weight: 0,
        threshold: [
          { min_value: 0, max_value: 5.9, label: 'green' },
          { min_value: 6.0, max_value: 9.0, label: 'yellow' },
          { min_value: 9.1, max_value: 24, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'work_commute_stress',
        label: 'Commute Stress: Rate commute stress',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 3, label: 'green' },
          { min_value: 4, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'red' },
        ],
        invertedScore: true,
      },
      {
        field: 'work_alignment_values',
        label: 'Alignment w/ Values: Rate alignment',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 4, label: 'red' },
          { min_value: 5, max_value: 7, label: 'yellow' },
          { min_value: 8, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'work_peer_recognition',
        label: 'Peer Recognition: Rate recognition',
        type: 'scale',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'occupational_role_alignment_coordinator',
        label: 'Role Alignment: Rate how aligned your role feels from 1 to 10',
        type: 'scale',
        target: 'coordinator',
        min: 1,
        max: 10,
        lowLabel: 'Low',
        highLabel: 'High',
        weight: 0.05,
        threshold: [
          { min_value: 1, max_value: 3, label: 'red' },
          { min_value: 4, max_value: 6, label: 'yellow' },
          { min_value: 7, max_value: 10, label: 'green' },
        ],
      },
      {
        field: 'occupational_sense_of_progress_coordinator',
        label: 'Sense of Progress: Do you feel a sense of progress in your work?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.03,
      },
      {
        field: 'occupational_work_life_boundaries_coordinator',
        label: 'Work/Life Boundaries: Were your work/life boundaries respected today?',
        type: 'dropdown',
        options: ['yes', 'no'],
        target: 'coordinator',
        weight: 0.04,
      },
    ],
  },
];


export default async function seedCheckInQuestions() {
  try {
    // await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing domains + questions
    await CheckInQuestion.deleteMany({});
    console.log('🗑️  Cleared existing CheckInQuestions');
    await Domain.deleteMany({});
    console.log('🗑️  Cleared existing Domains');

    const domainDocs = await Domain.insertMany(
      CHECKIN_DOMAINS.map((domain) => ({
        domainId: domain.id,
        domainLabel: domain.label,
        domainIcon: domain.icon,
        domainColor: domain.color,
        domainGradientColors: domain.gradientColors,
      }))
    );

    const domainById = new Map(domainDocs.map((d) => [d.domainId, d]));

    const docs: any[] = [];
    let order = 0;

    for (const domain of CHECKIN_DOMAINS) {
      for (const q of domain.questions) {
        const domainDoc = domainById.get(domain.id);
        if (!domainDoc) {
          throw new Error(`Missing domain for id: ${domain.id}`);
        }

        const question = q as {
          field: string;
          label: string;
          type: string;
          target: 'coordinator' | 'user';
          min?: number;
          max?: number;
          unit?: string;
          lowLabel?: string;
          highLabel?: string;
          options?: string[];
          optional?: boolean;
          invertedScore?: boolean;
          weight?: number;
          threshold?: { min_value: number; max_value: number; label: 'red' | 'yellow' | 'green' }[];
        };

        docs.push({
          field: question.field,
          label: question.label,
          type: question.type,
          target: question.target ?? 'user',
          domain: domainDoc._id,
          weight: question.weight ?? 1,
          min: question.min,
          max: question.max,
          threshold: question.threshold,
          unit: question.unit,
          lowLabel: question.lowLabel,
          highLabel: question.highLabel,
          options: question.options,
          optional: question.optional ?? false,
          invertedScore: question.invertedScore ?? false,
          order: order++,
          isActive: true,
        });
      }
    }
    await CheckInQuestion.insertMany(docs);
    console.log(`🌱 Seeded ${docs.length} CheckIn questions successfully`);

  } catch (error) {
    console.error('❌ Seeding failed:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

